### ISSUE TITLE
Encrypt the secrets on disk

### ISSUE THREAD

**Issue by muratg** [aspnet/UserSecrets#61]
cc @blowdart @Eilon

**Comment by blowdart** [comment]
We can't. We've discussed this before. There's no easy way to do this cross platform, and given that UserSecrets is only meant for dev, and not production machines it's very little return for a lot of effort.

**Comment by DamianEdwards** [comment]
@blowdart so, how do we expect customers to do cross-platform encryption?

**Comment by blowdart** [comment]
Users can quite happily create algorithms and keys, after all, that's how we do data protection.

However, key management and sharing is the problem, especially on operating systems where the only limitation on access is file ACLs.

Data protection itself kicks in long after config has been read, so we can't use that.

Then there's how to encrypt config, we're back to command lines, and how to get the keys up securely to production servers, because we can't put keys into the config file, otherwise we're back to machine key and all the mess that has historically had.

We've always said environment variables are the way to do config in production, even then environment variables aren't encrypted either.

So, like ruby, and secrets.yml, we don't encrypt.

**Comment by DamianEdwards** [comment]
OK then.
